"use client";

import React from "react";
import { Sparkles, Check, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";

export interface RecommendedAction {
  id: string;
  type: "Supply Chain" | "Staffing" | "Operations" | "Financial";
  title: string;
  description: string;
}

interface AlertItem {
  id: string;
  status: "Open" | "Actioned" | "Dismissed";
}

interface AIBriefProps {
  alerts: AlertItem[];
  lastSyncTime: string;
  onApplyAction: (id: string) => void;
  summary: string;
  recommendedActions: RecommendedAction[];
  isLoadingBrief: boolean;
}

export function AIBrief({
  alerts,
  lastSyncTime,
  onApplyAction,
  summary,
  recommendedActions,
  isLoadingBrief
}: AIBriefProps) {
  const getAlertStatus = (id: string) => {
    return alerts.find(a => a.id === id)?.status || "Open";
  };

  // Helper to color badge border/bg based on category type
  const getBadgeStyle = (type: string) => {
    switch (type) {
      case "Supply Chain":
        return "bg-destructive/10 text-destructive border border-destructive/20";
      case "Staffing":
        return "bg-amber-500/15 text-amber-700 dark:text-amber-500 border border-amber-500/20";
      case "Financial":
        return "bg-primary/10 text-primary border border-primary/20";
      default:
        return "bg-muted text-muted-foreground border border-border";
    }
  };

  const getContainerStyle = (type: string) => {
    switch (type) {
      case "Supply Chain":
        return "border-destructive/15 bg-destructive/5 hover:bg-destructive/10";
      case "Staffing":
        return "border-amber-500/20 bg-amber-500/5 hover:bg-amber-500/10";
      default:
        return "border-border bg-muted/30 hover:bg-muted/50";
    }
  };

  const getActionButtonStyle = (type: string) => {
    switch (type) {
      case "Supply Chain":
        return "bg-destructive hover:bg-destructive/90 text-white";
      case "Staffing":
        return "bg-amber-600 hover:bg-amber-650 text-white";
      default:
        return "bg-primary hover:bg-primary/90 text-primary-foreground";
    }
  };

  return (
    <div className="bg-card rounded-2xl border border-border shadow-sm overflow-hidden relative">
      {/* Sparkle top line indicator */}
      <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-primary via-indigo-500 to-purple-500" />
      
      <div className="p-6">
        {/* Header Section */}
        <div className="flex items-center justify-between pb-4 border-b border-border mb-5">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-primary/10 text-primary animate-pulse">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-foreground">Morning Operations Brief</h2>
              <p className="text-xs text-muted-foreground font-medium">Auto-generated by ClinicOps AI Agent • Refreshed {lastSyncTime}</p>
            </div>
          </div>
          <span className="text-[10px] font-semibold text-muted-foreground bg-muted px-2.5 py-1 rounded-md border border-border font-mono">
            Ollama Gemma 3 Active
          </span>
        </div>

        {/* Dynamic Summary / Loader */}
        {isLoadingBrief ? (
          <div className="space-y-4 py-3">
            <div className="flex items-center gap-2 text-sm text-muted-foreground font-medium">
              <RefreshCw className="w-4 h-4 animate-spin text-primary" />
              <span>Analyzing database anomalies and generating operations brief...</span>
            </div>
            <div className="space-y-2">
              <div className="h-4 bg-muted rounded w-full animate-pulse" />
              <div className="h-4 bg-muted rounded w-11/12 animate-pulse" />
              <div className="h-4 bg-muted rounded w-4/5 animate-pulse" />
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground leading-relaxed">
              {summary || "No operational anomalies detected in the synced dataset."}
            </p>
            
            {/* Recommended actions list */}
            <div className="space-y-3 pt-2">
              <h3 className="text-xs font-bold tracking-wider text-muted-foreground uppercase">
                Recommended Interventions ({recommendedActions.length})
              </h3>
              
              <div className="grid grid-cols-1 gap-3">
                {recommendedActions.length === 0 ? (
                  <p className="text-xs text-muted-foreground italic py-2">
                    No urgent interventions required at this time.
                  </p>
                ) : (
                  recommendedActions.map((action, index) => {
                    const status = getAlertStatus(action.id);
                    return (
                      <div
                        key={`${action.id}-${index}`}
                        className={`p-3.5 rounded-xl border flex flex-col sm:flex-row sm:items-center justify-between gap-3 transition-colors ${getContainerStyle(action.type)}`}
                      >
                        <div className="space-y-0.5">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className={`px-2 py-0.5 text-[9px] font-bold rounded uppercase ${getBadgeStyle(action.type)}`}>
                              {action.type}
                            </span>
                            <span className="text-xs font-semibold text-foreground">{action.title}</span>
                          </div>
                          <p className="text-xs text-muted-foreground">{action.description}</p>
                        </div>

                        {status === "Open" ? (
                          <Button
                            onClick={() => onApplyAction(action.id)}
                            className={`font-medium text-xs px-3 py-1.5 rounded-lg flex-shrink-0 cursor-pointer self-end sm:self-auto ${getActionButtonStyle(action.type)}`}
                          >
                            Approve Action
                          </Button>
                        ) : (
                          <span className="text-xs font-semibold text-emerald-600 dark:text-emerald-500 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-lg flex items-center gap-1.5 self-end sm:self-auto">
                            <Check className="w-3.5 h-3.5" /> Action Approved
                          </span>
                        )}
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
