import { NextResponse } from "next/server";
import { generateAlerts, getCriticalAlerts, getHighAlerts } from "@/lib/alert-engine";
import { sendTelegramMessage } from "@/lib/telegram";
import { verifyFivetranSignature } from "@/lib/fivetran-webhook-auth";

export const dynamic = "force-dynamic";

interface FivetranPayload {
  event?: string;
  data?: {
    status?: string;
  };
}

export async function POST(request: Request) {
  try {
    const rawBody = await request.text();

    const signature = request.headers.get("x-fivetran-signature-256");
    const isValid = verifyFivetranSignature(rawBody, signature);
    console.log("Signature verification result:", isValid);

    if (!isValid) {
      return NextResponse.json(
        { success: false, error: "Invalid Fivetran webhook signature" },
        { status: 401 }
      );
    }

    let payload: unknown = {};
    try {
      payload = JSON.parse(rawBody);
    } catch (error) {
      console.error("JSON Parse Error:", error);
    }

    const typedPayload = payload as FivetranPayload;
    const event = typedPayload?.event;
    const status = typedPayload?.data?.status;

    if (event === "sync_end" && status === "SUCCESSFUL") {
      console.log("Fivetran sync completed successfully. Running alert agent...");

      // a. Generate alerts & b. Update BigQuery alerts table
      console.log("Generating alerts...");
      await generateAlerts();
      console.log("Alerts generated and BigQuery alerts table updated.");

      // c. Fetch latest critical/high alerts
      console.log("Fetching critical alerts...");
      const criticalAlerts = await getCriticalAlerts();
      const highAlerts = await getHighAlerts();
      const alertsToNotify = [...criticalAlerts, ...highAlerts];
      console.log(`Fetched ${criticalAlerts.length} critical and ${highAlerts.length} high alerts to notify.`);

      // d. Send Telegram notifications
      console.log("Sending Telegram notifications...");
      for (const alert of alertsToNotify) {
        const displayType = alert.alert_type === "Supply Chain" ? "Medicine Stockout" : alert.alert_type;
        const message = `🚨 OCTOGRAM ALERT\n\nSeverity: ${alert.severity}\n\nType: ${displayType}\n\nTitle:\n${alert.title}\n\nDescription:\n${alert.description}\n\nStatus:\n${alert.status}\n\nGenerated by Octogram`;

        try {
          const success = await sendTelegramMessage(message);
          if (!success) {
            console.error("Telegram Error: sendTelegramMessage returned false");
          }
        } catch (error) {
          console.error("Telegram Error:", error);
        }
      }

      console.log("Webhook processing completed.");

      // e. Return success response
      return NextResponse.json({
        success: true,
        message: "Sync completion processed. Alerts updated and notified successfully.",
        notifiedCount: alertsToNotify.length
      });
    } else {
      console.log(`Fivetran Webhook: Ignored event '${event}' with status '${status}'.`);
      console.log("Webhook processing completed.");
      return NextResponse.json({
        success: true,
        message: `Ignored event '${event}' with status '${status}'. No action taken.`
      });
    }
  } catch (error: unknown) {
    console.error("Fivetran webhook processing failed:", error);
    const errorMessage = error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
